/* Drop Tables */

DROP TABLE BOOK_REVIEW CASCADE CONSTRAINTS;
DROP TABLE MYBOOK CASCADE CONSTRAINTS;
DROP TABLE BOOK CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;


/* Drop Sequences */

DROP SEQUENCE BOOK_REVIEW_SEQ;
DROP SEQUENCE BOARD_ID_SEQ;
DROP SEQUENCE MYBOOK_PK_SEQ;

/* Create Sequences */

CREATE SEQUENCE BOOK_REVIEW_SEQ;
CREATE SEQUENCE BOARD_ID_SEQ;
CREATE SEQUENCE MYBOOK_PK_SEQ
	START WITH 1
    MAXVALUE  10000
    CYCLE;

/* Create Tables */

CREATE TABLE MEMBER
(
	M_ID varchar2(20) NOT NULL,
	M_PASSWORD varchar2(20) NOT NULL,
	M_EMAIL varchar2(50) NOT NULL,
	M_NAME varchar2(20) NOT NULL,
	M_AGE number(4,0) NOT NULL,
	M_TEL varchar2(20) NOT NULL
);
ALTER TABLE MEMBER ADD CONSTRAINT MEM_PK_MID PRIMARY KEY(M_ID);


CREATE TABLE BOOK
(
	B_ID varchar2(40) NOT NULL,
	B_ISBN varchar2(100) NOT NULL,
	B_TITLE varchar2(200) NOT NULL,
	B_IMAGE varchar2(140),
	B_AUTHOR varchar2(40) NOT NULL,
	B_PRICE varchar2(40) NOT NULL,
	B_DISCOUNT varchar2(40),
	B_PUBLISHER varchar2(40) NOT NULL,
	B_PUBDATE varchar2(16) NOT NULL,
	B_DESCRIPTION varchar2(1000),
	B_FAVCNT number NOT NULL
);
ALTER TABLE BOOK ADD CONSTRAINT BOOK_PK_BID PRIMARY KEY(B_ID);
ALTER TABLE BOOK ADD CONSTRAINT BOOK_ISBN_UNQ UNIQUE(B_ISBN);
ALTER TABLE BOOK MODIFY B_FAVCNT NUMBER DEFAULT 0;


CREATE TABLE BOOK_REVIEW
(
	BR_ID number NOT NULL,
	BR_TITLE varchar2(100) NOT NULL,
	BR_REFUSER varchar2(20) NOT NULL,
	BR_REFBOOK varchar2(100) NOT NULL,
	BR_CONTENT varchar2(1000) NOT NULL,
	BR_REGDATE date NOT NULL
);
ALTER TABLE BOOK_REVIEW ADD CONSTRAINT BR_PK_BRID PRIMARY KEY(BR_ID);
ALTER TABLE BOOK_REVIEW ADD CONSTRAINT BR_FK_BY_BOOK 
    FOREIGN KEY(BR_REFBOOK) 
        REFERENCES BOOK(B_ISBN) ON DELETE CASCADE;
ALTER TABLE BOOK_REVIEW ADD CONSTRAINT BR_FK_BY_MEM 
    FOREIGN KEY(BR_REFUSER) 
        REFERENCES MEMBER(M_ID) ON DELETE CASCADE;


CREATE TABLE MYBOOK
(
    MB_ID number,
	M_ID varchar2(20 char),
	B_ISBN varchar2(100 char) NOT NULL
);

ALTER TABLE MYBOOK ADD CONSTRAINT MYBOOK_PK_BISBN PRIMARY KEY(MB_ID);
ALTER TABLE MYBOOK ADD CONSTRAINT MYBOOK_FK_BY_MEM 
    FOREIGN KEY(M_ID) 
        REFERENCES MEMBER(M_ID) ON DELETE CASCADE;
ALTER TABLE MYBOOK ADD CONSTRAINT MYBOOK_FK_BY_BOOK 
    FOREIGN KEY(B_ISBN) 
        REFERENCES BOOK(B_ISBN) ON DELETE CASCADE;


CREATE TABLE BOARD
(
	BD_ID number NOT NULL,
	BD_TITLE varchar2(200) NOT NULL,
    M_ID varchar2(20) NOT NULL,
    BD_CONTENT varchar2(2000) NOT NULL,
    BD_REGDATE date NOT NULL,
    BD_FILEPATH varchar2(500)
);
ALTER TABLE BOARD ADD CONSTRAINT BOARD_PK_BDID PRIMARY KEY(BD_ID);
ALTER TABLE BOARD ADD CONSTRAINT BOARD_FK_MEM 
    FOREIGN KEY(M_ID) 
    REFERENCES MEMBER(M_ID) ON DELETE CASCADE;
    
/* Insert Admin account */
INSERT INTO MEMBER(m_id, m_password, m_email,m_name, m_age, m_tel) VALUES('admin','admin','admin','admin',0,'admin');



